FROM node:20
LABEL maintainer="chienchi@lanl.gov"

RUN npm install pm2@latest -g
RUN mkdir -p /edgev3
COPY ./src/edge-v3/ /edgev3/
WORKDIR /edgev3

RUN cd /edgev3/installation; bash install-edgev3.sh;  
RUN apt-get -qq update ; apt-get -qq install -y --no-install-recommends vim curl mpich zlib1g-dev liblmdb-dev ca-certificates gnupg lsb-release\
    && update-ca-certificates \    
    && install -m 0755 -d /etc/apt/keyrings \
    && curl -sS https://download.docker.com/linux/debian/gpg | gpg --dearmor > /usr/share/keyrings/docker-ce.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-ce.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
    && apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin \
    && apt-get autoremove -y \
    && apt-get clean
RUN ln -s /usr/lib/x86_64-linux-gnu/libmpich.so.12 /usr/lib/x86_64-linux-gnu/libmpich.so.0 | true
RUN ln -s /usr/lib/aarch64-linux-gnu/libmpich.so.12 /usr/lib/aarch64-linux-gnu/libmpich.so.0 | true

RUN npm i -g mongosh
RUN cd /edgev3/webapp/client; sed -e 's|# VITE_API_URL=|VITE_API_URL=|g' -e 's|5000|8080|g' .env.example > .env; npm run build

RUN cd /edgev3/; pm2 start pm2.config.js; pm2 startup; pm2 save

RUN echo "alias ll='ls -alh'" >>  ~/.bashrc

EXPOSE 5000

#ENTRYPOINT ["pm2", "resurrect"]

#CMD ["pm2", "resurrect", "&&", "tail -f /dev/null"]
#CMD pm2 resurrect; pm2 reload all --update-env && tail -f /dev/null
CMD ["pm2-runtime", "pm2.config.js"]

